# Generated by Django 5.0 on 2023-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookswap_delete_books_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookswap',
            name='desc',
            field=models.TextField(default='Def desc', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='author',
            field=models.CharField(max_length=40, verbose_name='Автор'),
        ),
    ]
