# Generated by Django 5.0 on 2023-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookswap_desc_alter_bookswap_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookswap',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='desc',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
