# Generated by Django 5.0 on 2023-12-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bookswap_options_alter_bookswap_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookswap',
            name='deletable_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
